freshly_set/freshly_set/urls.py
from django.contrib import admin
from django.urls import path,re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("freshlyapp.urls")),
    path('freshlyapp/', include("freshlyapp.urls")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

freshly_set/freshlyapp/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.urls import re_path
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from .views import BlogListCreateView, BlogListView, CustomPasswordResetView, Register, search_blog, initiate_payment, mpesa_callback
from .views import PollDetailView, PollListCreateView, VerifyIDView, SubmitVote, IDVerificationUpdateView, IDVerificationDetailView, BannerListView, CategoryListCreateView, CategoryDetailView, vote_poll
from .views import *
from .forms import MyPasswordChangeForm, MyPasswordResetForm, MySetPasswordForm
from . import views
from django.conf import settings
from django.conf.urls.static import static


from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)


from .views import (
    BlogRetrieveUpdateDestroyAPIView,
    CommentListCreateAPIView, CommentRetrieveUpdateDestroyAPIView,
    LikeCreateAPIView, ShareCreateAPIView
)

urlpatterns = [
    path('register/', Register, name='register'),
    path('login/', login, name='login'),

    path('admin/', admin.site.urls),
    path('freshlyapp/token/', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('freshlyapp/token/refresh/',
         TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),


    # Catch-all route to serve React app for all frontend routes
    path('', TemplateView.as_view(template_name='index.html')),

    path('about-us/', TemplateView.as_view(template_name='index.html')),
    path("marketplace/", TemplateView.as_view(template_name="index.html")),
        path("signup/", TemplateView.as_view(template_name="index.html")),

    # path('blogs/', views.blogs, name='blogs'),
    path('freshlyapp/blogs/', BlogListView.as_view(), name='blog-list'),
    path('freshlyapp/create/', BlogListCreateView.as_view(),
         name='blog-list-create'),
    # path('create-blogs/', views.blog_create, name='blogs_create'),
    # path('freshlyapp/blogs/', views.blog_create, name='blog_create'),
    path('freshlyapp/search/', views.search_blog, name='search_blog'),


    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    # path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='password_change.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'), name='password_change_done'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
    #     path('products/', views.products, name='products'),
    path('services/', views.services, name='services'),
    path('profile/', views.GetUserProfile.as_view(), name='profile'),
    path('profile/update/', UpdateUserProfile.as_view(), name='user-profile-update'),

    # path('blogs/', BlogListCreateAPIView.as_view(), name='blog_list_create'),
    path('blogs/<int:pk>/', BlogRetrieveUpdateDestroyAPIView.as_view(),
         name='blog_detail'),
    path('comments/', CommentListCreateAPIView.as_view(),
         name='comment_list_create'),
    path('comments/<int:pk>/',
         CommentRetrieveUpdateDestroyAPIView.as_view(), name='comment_detail'),
    path('likes/', LikeCreateAPIView.as_view(), name='like_create'),
    path('shares/', ShareCreateAPIView.as_view(), name='share_create'),
    # path('search_blog/<int:pk>/', views.search_blog, name='search_blog'),
    path('search_blog/', views.search_blog, name='search_blog'),

    path('freshlyapp/token/', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('freshlyapp/token/refresh/',
         TokenRefreshView.as_view(), name='token_refresh'),

    # Poll URLs
    path('freshlyapp/polls/', PollListCreateView.as_view(), name='poll-list-create'),
    path('polls/<int:pk>/', PollDetailView.as_view(), name='poll-detail'),
#     path('polls/<int:pk>/vote/', SubmitVote.as_view(), name='vote-create'),
    path('submit-vote/', SubmitVote, name='submit_vote'),

     # Testing new format
     path('api/polls/', PollListView.as_view(), name='poll-list'),
#     path('api/polls/<int:pk>/vote/', PollVoteView.as_view(), name='poll-vote'),

        path('api/polls/<int:poll_id>/vote/', views.vote_poll, name='vote_poll'),

    # Verifications
    path('freshlyapp/verification/verify/',
         VerifyIDView.as_view(), name='verify-id'),
    path('freshlyapp/verification/', IDVerificationUpdateView.as_view(),
         name='id-verification-update'),
    path('freshlyapp/verification/detail/',
         IDVerificationDetailView.as_view(), name='id-verification-detail'),


    # product urls
    path('products/', ProductListView.as_view(), name='list-products'),
    path('products/create/', CreateProduct.as_view(), name='create-product'),
    path('products/<int:pk>/', RetrieveProduct.as_view(), name='retrieve-product'),
    path('products/<int:pk>/update/',
         UpdateProduct.as_view(), name='update-product'),
    path('products/<int:pk>/delete/',
         DeleteProduct.as_view(), name='delete-product'),


    # Banner URL

    path('freshlyapp/banners/', BannerListView.as_view(), name='banner-list'),



    # Category URL

    path('freshlyapp/categories/', CategoryListCreateView.as_view(),
         name='category-list-create'),
    path('freshlyapp/categories/<int:pk>/', CategoryDetailView.as_view(),
         name='category-detail'),



    # CART URLS
    path('cart/', views.get_cart_instance, name='get_cart'),
    path('cart/add/', views.add_to_cart, name='add_to_cart'),
    path('cart/update/', views.update_quantity, name='update_quantity'),
    path('cart/remove/', views.remove_from_cart, name='remove_from_cart'),




    #order url
    path('orders/', views.my_orders, name='my_orders'),
    path('order/<str:tracking_no>/', views.view_order, name='view_order'),
    path('order/cancel/<str:tracking_no>/', views.cancel_order, name='cancel_order'),
    path('order/create/', views.create_order, name='create_order'),



   #notification url
    path('notifications/', NotificationListView.as_view(), name='notification-list'),

   # Payment urls
    path('api/initiate-payment/', initiate_payment, name='initiate-payment'),
    path('api/mpesa-callback/', mpesa_callback, name='mpesa-callback'),


   #Verified Farmers
    path('verified-farmers/', FarmerListView.as_view(), name='verified-farmers'),

    
]

freshly_set/freshlyapp/models.py
# from argon2 import hash_password
import os
from PIL import Image
from django.core.exceptions import ValidationError
from better_profanity import profanity
from datetime import timezone
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.conf import settings
import boto3
import re



"""
class AppUserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, name, phone, password, **extra_fields):

        values = [email, name, phone]
        field_value_map = dict(zip(self.model.REQUIRED_FIELDS, values))

        for field_name, value in field_value_map.items():
            if not value:
                raise ValueError('The {} value must be set'.format(field_name))

        email = self.normalize_email(email)

        user = self.model(
            email=email,
            name=name,
            phone=phone,
            **extra_fields
        )

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, name, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, name, phone, password, **extra_fields)

    def create_superuser(self, email, name, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        
        return self._create_user(email, name, phone, password, **extra_fields)

class AppUser(AbstractBaseUser, PermissionsMixin):
    user_id = models.AutoField(primary_key=True)
    email = models.EmailField(max_length=255, unique=True)
    username = models.CharField(max_length=32, blank=False, null=False)
    name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=30, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)

    objects = AppUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [
        'username', 
        'name',  
        'phone'
    ]

    def __str__(self):
        return self.email
"""


# models.py (additional models)
from django.db import models
from django.contrib.auth.models import User

# Cart Model


    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15, blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    remember_me = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(
        upload_to='static/images/Categories', null=True, blank=True)
    bgColor = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    desc = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    qtty = models.IntegerField(default=0)
    unit = models.CharField(max_length=255, null=True,
                            blank=True, default="PACKET")
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='products', blank=True, null=True)
    image = models.ImageField(
        upload_to='static/images/Products', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.name

    def clean(self):
        # Name validation
        if len(self.name.strip()) == 0:
            raise ValidationError({'name': 'Name cannot be empty.'})
        if len(self.name) > 255:
            raise ValidationError(
                {'name': 'Name cannot exceed 255 characters.'})

        # Price validation
        if self.price < 0:
            raise ValidationError({'price': 'Price cannot be negative.'})
        if self.price < 0.01 or self.price > 99999.99:
            raise ValidationError(
                {'price': 'Price must be between 0.01 and 99999.99.'})
        if self.price.as_tuple().exponent < -2:
            raise ValidationError(
                {'price': 'Price cannot have more than two decimal places.'})

        # Quantity validation
        if self.qtty < 0:
            raise ValidationError({'qtty': 'Quantity cannot be negative.'})
        if self.qtty > 10000:
            raise ValidationError({'qtty': 'Quantity cannot exceed 10,000.'})

        # Description validation
        if len(self.desc) < 10:
            raise ValidationError(
                {'desc': 'Description is too short. It should be at least 10 characters long.'})
        if profanity.contains_profanity(self.desc):
            raise ValidationError(
                {'desc': 'Description contains prohibited or inappropriate content.'})

        # Image validation
        if self.image:
            ext = os.path.splitext(self.image.name)[1].lower()
            valid_extensions = ['.jpg', '.jpeg', '.png']
            if ext not in valid_extensions:
                raise ValidationError(
                    {'image': 'Unsupported file extension. Allowed extensions are: .jpg, .jpeg, .png'})

            if self.image.size > 5 * 1024 * 1024:
                raise ValidationError(
                    {'image': 'Image file size cannot exceed 5MB.'})

            image = Image.open(self.image)
            width, height = image.size
            if width < 800 or height < 600:
                raise ValidationError(
                    {'image': 'Image resolution too low. Minimum resolution is 800x600.'})
            if width > 4000 or height > 3000:
                raise ValidationError(
                    {'image': 'Image resolution too high. Maximum resolution is 4000x3000.'})

    def save(self, *args, **kwargs):
        # Call the clean method to ensure validations are checked before saving
        self.clean()
        super(Product, self).save(*args, **kwargs)


class Review(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='reviews')
    rating = models.IntegerField()
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Review for {self.product.name} by {self.id}'


class Farmer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.user.username  # Use the username field from the User model


class Garden(models.Model):
    name = models.CharField(max_length=100, default='DEFAULT VALUE')
    location = models.CharField(max_length=255)
    size = models.CharField(max_length=100)
    features = models.TextField()
    description = models.CharField(max_length=140, default='DEFAULT VALUE')

    def __str__(self):
        return self.location


class Service(models.Model):
    SERVICE_TYPES = (
        ('installation', 'Installation'),
        ('consultation', 'Consultation'),
        ('rental', 'Renting Equipment'),
        ('selling', 'Selling Equipment'),
    )
    type = models.CharField(max_length=50, choices=SERVICE_TYPES)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.get_type_display()} - {self.price}'


class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,  # Allow null temporarily
                             blank=True)  # Allow blank temporarily
    title = models.CharField(max_length=200)
    content = models.TextField()
    comments = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    shares = models.IntegerField(default=0)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    image = models.ImageField(upload_to='blog_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Blog")
        verbose_name_plural = _("Blogs")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

# Added models for Comment, Like, and Share.


class Comment(models.Model):
    blog = models.ForeignKey(
        Blog, related_name='blog_comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content


class Like(models.Model):
    blog = models.ForeignKey(
        Blog, related_name='blog_likes', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('blog', 'user')


class Share(models.Model):
    blog = models.ForeignKey(
        Blog, on_delete=models.CASCADE, related_name='blog_shares')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    shared_at = models.DateTimeField(auto_now_add=True)


# Poll for voting yes / no maybe and others

freshly_set/freshlyapp/templates/about.html
<!DOCTYPE html>
<html>
<head>
    <title>About Freshly Farms</title>
</head>
<body>
    <h1>About Freshly Farms</h1>
    <p>Company history, mission, vision, team members, and contact information.</p>
</body>
</html>

freshly_set/freshlyapp/templates/blogs.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ blog.title }}</title>
</head>
<body>
    <h1>{{ blog.title }}</h1>
    <p>{{ blog.content }}</p>
    {% if blog.image %}
    <img src="{{ blog.image.url }}" alt="{{ blog.title }}" />
    {% endif %}
    <a href="{% url 'blog_update' blog.slug %}">Edit</a>
    <a href="{% url 'blog_delete' blog.slug %}">Delete</a>
    <a href="{% url 'blog_list' %}">Back to list</a>
</body>
</html>

freshly_set/freshlyapp/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Freshly Farms</title>
</head>
<body>
    <h1>Welcome to Freshly Farms</h1>
    <p><a href="{% url 'signup' %}">Sign Up</a> or if you are registered already <a href="{% url 'login' %}">Log In</a></p>
</body>
</html>

freshly_set/freshlyapp/templates/index.html
<<<<<<< HEAD
<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Freshly Farms revolutionizes urban agriculture with sustainable vertical farming. We deliver fresh, locally sourced produce straight to your door, ensuring the highest quality from farm to table."/><meta name="keywords" content="Organic farming"/><meta name="author" content="Freshly Farms"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet"><link rel="icon" href="/static/media/logoWhite.png"/><link rel="manifest" href="/manifest.json"/><title>Freshly Farms | Revolutionizing Agriculture for a Sustainable Future</title><script defer="defer" src="/static/js/main.b48abfb3.js"></script><link href="/static/css/main.fb03fe70.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>
=======
<<<<<<< HEAD
<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Freshly Farms revolutionizes urban agriculture with sustainable vertical farming. We deliver fresh, locally sourced produce straight to your door, ensuring the highest quality from farm to table."/><meta name="keywords" content="Organic farming"/><meta name="author" content="Freshly Farms"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet"><link rel="icon" href="/static/media/logoWhite.png"/><link rel="manifest" href="/manifest.json"/><title>Freshly Farms | Revolutionizing Agriculture for a Sustainable Future</title><script defer="defer" src="/static/js/main.6161c837.js"></script><link href="/static/css/main.538c3dcc.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>
=======
<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Freshly Farms revolutionizes urban agriculture with sustainable vertical farming. We deliver fresh, locally sourced produce straight to your door, ensuring the highest quality from farm to table."/><meta name="keywords" content="Organic farming"/><meta name="author" content="Freshly Farms"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet"><link rel="icon" href="/static/media/logoWhite.png"/><link rel="manifest" href="/manifest.json"/><title>Freshly Farms | Revolutionizing Agriculture for a Sustainable Future</title><script defer="defer" src="/static/js/main.3b16429c.js"></script><link href="/static/css/main.538c3dcc.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>
>>>>>>> origin/Simanga-dev
>>>>>>> d7012775ac16edef7e37884ce9792cae0a604851

freshly_set/freshlyapp/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">  <!-- Example linking to a CSS file -->
  
</head>
<body>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <p>Don't have an account? <a href="{% url 'register' %}">Sign up</a></p>
    <p>Forgot your password? <a href="{% url 'password_reset' %}">Reset password</a></p>
</body>
</html>

freshly_set/freshlyapp/templates/password_change.html
<!DOCTYPE html>
<html>
<head>
    <title>Password Change</title>
</head>
<body>
    <h2>Change Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Change Password</button>
    </form>
</body>
</html>

freshly_set/freshlyapp/templates/password_change_done.html
<!DOCTYPE html>
<html>
<head>
    <title>Password Change Done</title>
</head>
<body>
    <h2>Password Change Successful</h2>
    <p>Your password has been changed successfully.</p>
</body>
</html>

freshly_set/freshlyapp/templates/password_reset.html
<!DOCTYPE html>
<html>
<head>
    <title>Reset Password</title>
</head>
<body>
    <h2>Reset Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <p>Remember your password? <a href="{% url 'login' %}">Login</a></p>
</body>
</html>

freshly_set/freshlyapp/templates/password_reset_complete.html
<!DOCTYPE html>
<html>
<head>
    <title>Password Reset Complete</title>
</head>
<body>
    <h2>Password Reset Complete</h2>
    <p>Your password has been set. You can now log in with your new password.</p>
</body>
</html>

freshly_set/freshlyapp/templates/password_reset_confirm.html
<!DOCTYPE html>
<html>
<head>
    <title>Password Reset Confirm</title>
</head>
<body>
    <h2>Set New Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Set New Password</button>
    </form>
</body>
</html>

freshly_set/freshlyapp/templates/password_reset_done.html
<!DOCTYPE html>
<html>
<head>
    <title>Password Reset Done</title>
</head>
<body>
    <h2>Password Reset Email Sent</h2>
    <p>We've emailed you instructions for setting your password.</p>
</body>
</html>

freshly_set/freshlyapp/templates/products.html
<!DOCTYPE html>
<html>
<head>
    <title>Products - Freshly Farms</title>
</head>
<body>
    <h1>Your Products</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Product</button>
    </form>
    <ul>
        {% for product in products %}
        <li>{{ product.name }} - {{ product.description }} - ${{ product.price }}</li>
        {% endfor %}
    </ul>
</body>
</html>

freshly_set/freshlyapp/templates/profile.html
<!DOCTYPE html>
<html>
<head>
    <title>Profile - Freshly Farms</title>
</head>
<body>
    <h1>Your Profile</h1>
    <p>Name: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <a href="{% url 'logout' %}">Log Out</a>
</body>
</html>

freshly_set/freshlyapp/templates/signup.html
<!DOCTYPE html>
<html>
<head>
    <title>Register</title>
</head>
<body>
    <h2>SignUp</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">SignUp</button>
    </form>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</body>
</html>